- components/UI/Button.js
- components/card/RecipeCard.js
- components/icons/ArrowPointer.js
- components/icons/DateIcon.js
- pages/_app.js
- pages/index.js
- styles/globals.css
created button & recipe card components and also added css styling to the globals.css & icons
> Loading-recipes

- lib/view-recipes.js
Created the function that gets the 100 recipes form the api
> Adds function that gets the 100 recipes

- pages/index.js
Fixed the home page JSX and inserted the return statement
> Fixed home page

- components/tags/RecipeTags.js
This code takes a prop called tags, which should be an array of strings. The component maps over the tags array and creates a <button> element for each tag. Each button is assigned a unique key based on the tag itself to help React efficiently manage updates. The resulting buttons are wrapped in a <div> container.
,To show the tags associated with a recipe. The code ensures that each tag is uniquely identified and properly rendered as a button element.
> Added RecipeTags component, to display all tags.

- components/card/RecipeCard.js
- lib/view-recipes.js
- styles/globals.css
Fixed the recipe card styling for responsiveness and also modified the body styling.
Added the getCategories & getAllergens
> Card-fixing

- components/card/RecipeCard.js
- components/icons/ArrowPointer.js
- components/icons/DateIcon.js
- components/icons/ServingIcon.js
- components/icons/TimeIcon.js
- components/recipe-collection/RecipeList.js
- styles/globals.css
Modified the time component.
Modified the card component.
> Add time  and card modification

- components/recipe-collection/RecipeList.js
A link was added for detail page routing
> Added the detail page routing

- components/details/details.js
- components/recipe-collection/RecipeList.js
- pages/api/[recipeId].js
- pages/api/recipes.js
- pages/recipes/[recipeId].js
Changed limit from 100 recipes to 2000 recipes and also fixed the recipe details page errors
> loading 2000 recipes & fixed detail page

- components/recipe-collection/RecipeList.js
- components/skeletonCard/skeleton.js
- helpers/db.js
- lib/view-recipes.js
- pages/api/recipes.js
- pages/index.js
Adde skeleton and changed recipe request to 100
> Edit rendered recipes

- components/recipe-collection/RecipeList.js
- lib/view-recipes.js
- pages/api/recipes.js
- pages/index.js
Fixed the load more button count so that it shows the number of all documents in the mongodb collection
> Fixed load more btn count

- components/card/RecipeCard.js
Just added a div for user friendliness on the home page
> Styling Home page

- components/allergens/allergens.js
- components/details/details.js
Added and displayed allergens in details.js
> Added allergens

- components/details/details.js
- components/details/instructions/instructions.js
- pages/api/updateRecipe/[recipeId].js
> Adds description edit

- components/search-functionality/search-bar.js
- pages/index.js
Added a basic structure of the search functionality
> Added search-bar basic structure

- components/navbar/navbar.js
- package-lock.json
- package.json
Used different colors and fonts
> Modified navbar

- components/card/RecipeCard.js
- components/navbar/navbar.js
- components/recipe-collection/RecipeList.js
- pages/api/recipes.js
- pages/index.js
- pages/recipes/favorites/index.js
Added the favorites page and the favorites saving to the recipes collection in mongoDB database
> Adds favorites functionality

- components/card/RecipeCard.js
- pages/recipes/favorites/index.js
Added the icons to the recipe card that show if recipe is favorite or not.
Also removed prompt when the recipe is marked as favorite
> Fix the favorite functionality

- components/card/RecipeCard.js
> Fixed favorite button

- components/recipe-collection/RecipeList.js
- lib/view-recipes.js
- pages/api/pre-render.js
- pages/index.js
> fixed recipe list Grid

- components/details/details.js
addition of the missing prop that had to be passed to instructions component in the details.js file.
> added instructions recipe.Id prop

- lib/view-recipes.js
- pages/api/favorites.js
- pages/recipes/favorites/index.js
I fixed the favorites logic so that it also works after filters
> Fixed favorites logic

- database/database.js
Added  maxIdleTimeMS in the mongo connection settings
> Mongo connection improvements

- components/recipe-collection/RecipeList.js
- components/search-functionality/Modal.js
- components/search-functionality/search-bar.js
- package-lock.json
- package.json
- pages/index.js
Fixed the highlighting to be in sync with the new code that was implimented when we introduced useContext
> Fixing-highlighting-with-updated-code

- components/search-functionality/Modal.js
- pages/index.js
Fix the loadmore button functionality and also the filtering logic on filtering by multiple tags
> UseContext-and-filtering

- components/card/RecipeCard.js
- components/icons/TimeIcon.js
- components/time/TimeDisplay.js
re-arranged the card and it's size
> Edited layout of the cards

- components/search-functionality/Modal.js
- components/search-functionality/search-bar.js
Added tags multi select for good user experience
> Fixing of tags suggestion

- components/search-functionality/search-bar.js
- pages/api/filter.js
Updated the sorting for user friendliness
> Updated sorting

- components/search-functionality/search-bar.js
fixed the problem of clicking the Value Several times
> fixed the handle sort function

- components/search-functionality/search-bar.js
- pages/api/filter.js
added the sorting functionality for instructions
> updated the sorting 

- components/card/RecipeCard.js
- components/recipe-collection/RecipeList.js
- components/search-functionality/search-bar.js
- lib/view-recipes.js
- pages/api/favorites.js
- pages/recipes/favorites/index.js
Fixed the favorites state to update immediately when a favorite is unmarked as favorite
> Favorites-logic-refacturing

- components/card/RecipeCard.js
- next.config.js
added a configuration in the next-config file and removed the layout to fix errors in the console.
> Fixed the missing pictures

- components/search-functionality/search-bar.js
removed the problem of the  blank Page that shows the error component before loading the sorted Data.
> fixed the sorting

- components/description/description.js
- components/details/details.js
- components/details/ingredients/ingredients.js
- components/details/instructions/instructions.js
- components/details/nutrition/nutrition.js
- components/tags/RecipeTags.js
> Updating the detail page

- components/card/RecipeCard.js
- components/search-functionality/Modal.js
- pages/api/filter.js
Added sorting and filtering aggregation to the app
> Added aggregation

- components/description/description.js
Forgot to add the same functionality as the instructions to the description
> description save function added

- components/search-functionality/Modal.js
- components/search-functionality/filterContext.js
- components/search-functionality/search-bar.js
- pages/index.js
- added useContext for search term
> Search term use context

- components/navbar/navbar.js
- components/recipe-collection/RecipeList.js
- components/search-functionality/search-bar.js
Fixing navigation bar and sorting bar
> fixing navbar and sort bar

- components/navbar/navbar.js
- components/search-functionality/search-bar.js
Removed the span inside <option> in the search-bar
> Fix the main bugs

- components/card/RecipeCard.js
- components/recipe-collection/RecipeList.js
- components/search-functionality/Modal.js
- components/search-functionality/search-bar.js
- pages/404.js
- pages/contact.js
- pages/index.js
- pages/recipes/[recipeId].js
- pages/recipes/favorites/index.js
Fixed a few issues we had in relation to the entire functionality of the app
>  filtering functionality

- components/search-functionality/Modal.js
- pages/api/filter.js
- styles/globals.css
Fixed the instructions filters to filter by the selected instruction filter
> Fixed instructions filter

- components/allergens/allergens.js
- components/description/description.js
- components/details/details.js
- components/details/ingredients/ingredients.js
- components/details/instructions/instructions.js
- components/error/Error.js
- components/error/NetworkError.js
- components/search-functionality/Modal.js
- components/search-functionality/search-bar.js
- components/tags/RecipeTags.js
- pages/api/filter.js
- pages/index.js
- Fixed the animation when making requests
- Cleaned up the codebase in terms of removing unused imports and props
- Corrected the filtered recipes count
> Filtering & Animation fix

- components/search-functionality/search-bar.js
> Sort bar quick fix

- components/UI/ScrollArrowButtons.js
- components/card/RecipeCard.js
- components/navbar/navbar.js
- components/search-functionality/search-bar.js
- pages/index.js
- styles/globals.css
- removed the view recipe button.
- Inserted scroll to top and scroll down for user experience
> removed view recipe button

- components/card/RecipeCard.jsx
- components/description/description.jsx
- components/details/details.jsx
- components/details/instructions/instructions.jsx
- components/recipe-collection/RecipeList.jsx
- components/search-functionality/Modal.jsx
- components/search-functionality/search-bar.jsx
- pages/contact.jsx
- pages/index.jsx
- tailwind.config.js
- Added better UX
- Hooked the error component to the project
> Network error & UX fix
